/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stomatology;

import java.awt.Color;
import javafx.scene.Parent;
import javax.swing.JDialog;

/**
 *
 * @author TemplaRus
 */
public class Panel_Tooth_Surface_status extends javax.swing.JPanel
{

    int figure_id = 0;
    int status_id = 0;
    boolean isPervich = false;
    JDialog gd;

    public Panel_Tooth_Surface_status(Integer[] color_number, String text, int status_id, int figure_id, JDialog gd, boolean isPervich) //убрать tooth_number
    {
        this.figure_id = figure_id;
        this.status_id = status_id;
        this.gd = gd;
        this.isPervich = isPervich;
        initComponents();
        jPanel1.setBackground(new Color(color_number[0], color_number[1], color_number[2]));
        jLabel1.setText(text);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 153));
        setPreferredSize(new java.awt.Dimension(150, 17));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 17));
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 17));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 20, 17);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("TEXT");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 17));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 17));
        add(jLabel1);
        jLabel1.setBounds(20, 0, 130, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

        //Pervich_Popup.statusZub.get(figure_id).setIdSprPervich(status_id);
        if (isPervich)
        {
            Object_Tooth.TP.getStatusGrZub().get(figure_id).setIdPervich(status_id);
            Object_Tooth.TP.getStatusGrZub().get(figure_id).setColor(Start.sDB.getColorPervich(status_id));
            Object_Tooth.TP.Redraw();
            Object_Tooth.TP.repaint();
        }
        else
        {
            Object_Tooth.RSP.getStatusGrZub().get(figure_id).setIdRab(status_id);
            Object_Tooth.RSP.getStatusGrZub().get(figure_id).setColor(Start.sDB.getColorPervich(status_id));
            Object_Tooth.RSP.Redraw();
            Object_Tooth.RSP.repaint(); 
        }
        Button_Tooth.TSP.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
