/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stomatology.spravochniki;

import stomatology.DatabaseTableModel;
import stomatology.Start;

/**
 *
 * @author Asus
 */
public class SprPervichIskRab extends javax.swing.JFrame {

    /**
     * Creates new form SprPervich
     */
    public SprPervichIskRab() {
        initComponents();
        sprPervichTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        sprPervichTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        sprPervichTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        sprPervichTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        sprPervichTable.doLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DatabaseTableModel dbm = new DatabaseTableModel(false);
        sprPervichTable = new javax.swing.JTable();
        addRab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        sprPervichTable.setModel(dbm);
        try {
            dbm.setDataSource(Start.sDB.getRSSprPervichData());
        } catch (Exception ex){
            System.out.println("Создание таблицы справочник первичного обследования: ошибка доступа к RS"+ ex);
        }
        sprPervichTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sprPervichTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sprPervichTable);

        addRab.setText("Закрыть");
        addRab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addRab, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRab, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRabActionPerformed
        dispose();
    }//GEN-LAST:event_addRabActionPerformed

    private void sprPervichTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sprPervichTableMouseClicked
     Integer idPervich = (Integer) sprPervichTable.getValueAt(sprPervichTable.getSelectedRow(), 0);
     String namePervich = (String)sprPervichTable.getValueAt(sprPervichTable.getSelectedRow(), 1);
     String nameKateg = (String)sprPervichTable.getValueAt(sprPervichTable.getSelectedRow(), 3);
     

     SprPervichIskRabEdit edit = new SprPervichIskRabEdit(idPervich,namePervich,nameKateg);
     edit.setVisible(true);
    }//GEN-LAST:event_sprPervichTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SprPervichIskRab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SprPervichIskRab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SprPervichIskRab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SprPervichIskRab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SprPervichIskRab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sprPervichTable;
    // End of variables declaration//GEN-END:variables
}
